In [1]:
import numpy as np;
import matplotlib.pyplot as plt;

In [2]:
data = np.loadtxt("test.txt");
datanew  = data[ np.lexsort((data[:,1],data[:,0])) ]


In [3]:
data[0:5, 0:4]

array([[ 4.30e+01,  0.00e+00, -3.15e-03,  9.00e+00],
       [ 4.60e+01,  0.00e+00, -1.80e-03,  9.00e+00],
       [ 3.70e+01,  0.00e+00, -5.85e-03,  9.00e+00],
       [ 1.20e+01,  0.00e+00, -1.71e-02,  9.00e+00],
       [ 4.40e+01,  0.00e+00, -2.70e-03,  9.00e+00]])

In [4]:
datanew[0:5, 0:4]

array([[ 0.    ,  0.    , -0.0225,  9.    ],
       [ 0.    ,  1.    , -0.0225,  9.04  ],
       [ 0.    ,  2.    , -0.0225,  9.08  ],
       [ 0.    ,  3.    , -0.0225,  9.12  ],
       [ 0.    ,  4.    , -0.0225,  9.16  ]])

In [5]:
AVIndex=datanew[:,0:2]
MomProb=datanew[:,4:]

In [6]:
datanew[50*51+25,:]

array([5.00000000e+01, 2.50000000e+01, 0.00000000e+00, 1.00000000e+01,
       6.70021128e-04, 1.49843077e-02, 1.05209344e-02, 6.38614046e-02,
       3.00557747e-01, 2.58956241e-01, 3.39602103e-02, 1.06921283e-01,
       2.01417514e-01, 7.48016213e-03, 6.70175240e-04])

In [6]:
np.savetxt("AVIndex.txt",AVIndex)

In [7]:
np.savetxt("MomProb.txt",MomProb)

In [ ]:
AVIndex

In [ ]:
x=[];
for i in range(len(MomProb)):
    x.append(np.sum(MomProb[i,:])-1.0)

In [ ]:
plt.plot(x);

In [11]:
datanew[51*50,:]

array([5.00000000e+01, 0.00000000e+00, 3.13278139e-04, 1.00199808e-02,
       4.02486714e-03, 1.11524926e-01, 2.11285885e-01, 2.53839817e-01,
       3.77708799e-02, 2.14249787e-01, 1.40336302e-01, 1.64093832e-02,
       2.24894319e-04])